# Generated by Django 5.1.6 on 2025-02-28 10:46

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Подробнее')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MbankImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Мбанк лого')),
                ('Mbank', models.CharField(max_length=20, verbose_name='Мбанк')),
                ('ObankImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='ОБанк лого')),
                ('Obank', models.CharField(max_length=20, verbose_name='ОБанк')),
                ('CompanionImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Компанион лого')),
                ('Companion', models.CharField(max_length=20, verbose_name='Компанион')),
                ('BakaiBankImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Бакай Банк лого')),
                ('BakaiBank', models.CharField(max_length=20, verbose_name='Бакай Банк')),
            ],
            options={
                'verbose_name': 'Банковские реквезиты',
                'verbose_name_plural': 'Банковские реквезиты',
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='', verbose_name='Сертификаты')),
            ],
            options={
                'verbose_name': 'Сертификаты',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Основатели',
                'verbose_name_plural': 'Основатели',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.TextField(verbose_name='Обязанности')),
                ('duty_file', models.FileField(upload_to='', verbose_name='Файл с информацией')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантия',
            },
        ),
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('disease', models.CharField(max_length=100, verbose_name='Заболевание')),
                ('urgency', models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Очень срочно', 'Очень срочно')], max_length=255, null=True, verbose_name='Насколько срочно')),
                ('sum', models.CharField(max_length=100, verbose_name='Сумма сбора')),
                ('collected', models.CharField(max_length=100, verbose_name='Собранная сумма')),
                ('active', models.BooleanField(default=False, verbose_name='Активно для сбора')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Подробнее')),
            ],
            options={
                'verbose_name': 'Нуждающийся',
                'verbose_name_plural': 'Нуждающийся',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('img', models.ImageField(upload_to='volunteers_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Валантеры',
                'verbose_name_plural': 'Валантеры',
            },
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='volunteers_qr/', verbose_name='QR_код')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbr.needy', verbose_name='Пациент')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbr.volunteer', verbose_name='Волонтёр')),
            ],
            options={
                'verbose_name': 'QR код',
                'verbose_name_plural': 'QR коды',
            },
        ),
    ]
