# Generated by Django 5.1.7 on 2025-04-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needydisplay',
            name='needy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jbr.needyprofile'),
        ),
    ]
