# Generated by Django 5.1.6 on 2025-02-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='guarantee',
            options={'verbose_name': 'Гарантия', 'verbose_name_plural': 'Гарантия'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Больные', 'verbose_name_plural': 'Больные'},
        ),
    ]
