# Generated by Django 5.1.7 on 2025-03-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка нуждающегося',
                'verbose_name_plural': 'Заявка нуждающегося',
            },
        ),
    ]
