# Generated by Django 5.1.6 on 2025-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='urgency',
        ),
        migrations.AddField(
            model_name='needy',
            name='data',
            field=models.IntegerField(default=1, verbose_name='До какого числа сбор '),
            preserve_default=False,
        ),
    ]
