# Generated by Django 5.1.7 on 2025-03-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0002_application_needy'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='valunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jbr.volunteer', verbose_name='Валантёр'),
            preserve_default=False,
        ),
    ]
