# Generated by Django 5.1.7 on 2025-04-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0002_alter_needydisplay_needy_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needyprofile',
            options={},
        ),
    ]
