# Generated by Django 5.1.6 on 2025-03-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0003_alter_needy_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbr.needy', verbose_name='Нуждающийся'),
        ),
    ]
