# Generated by Django 5.1.7 on 2025-04-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0003_alter_needyprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpedneedy',
            name='collected',
            field=models.IntegerField(blank=True, null=True, verbose_name='Собранная сумма'),
        ),
        migrations.AddField(
            model_name='helpedneedy',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма для сбора'),
        ),
    ]
