# Generated by Django 5.1.6 on 2025-02-19 12:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0003_patients_active_patients_collected_patients_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mbank', models.CharField(max_length=20, verbose_name='Мбанк')),
                ('Obank', models.CharField(max_length=20, verbose_name='ОБанк')),
                ('Companion', models.CharField(max_length=20, verbose_name='Компанион')),
                ('BakaiBank', models.CharField(max_length=20, verbose_name='Бакай Банк')),
            ],
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='founder',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Подробнее'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
