# Generated by Django 5.1.7 on 2025-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0003_needyprofile_valunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needyprofile',
            name='valunteer',
        ),
        migrations.AddField(
            model_name='needyprofile',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='jbr.volunteer', verbose_name='Волонтёры'),
        ),
    ]
