# Generated by Django 5.1.6 on 2025-02-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0004_bankdetails_founders_remove_aboutus_about_us_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Банковские реквезиты', 'verbose_name_plural': 'Банковские реквезиты'},
        ),
        migrations.AlterModelOptions(
            name='founders',
            options={'verbose_name': 'Основатели', 'verbose_name_plural': 'Основатели'},
        ),
    ]
