# Generated by Django 5.1.7 on 2025-03-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0004_remove_needyprofile_valunteer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentsneedy',
            name='dokument',
            field=models.CharField(max_length=200, verbose_name='Документ'),
        ),
    ]
