# Generated by Django 5.1.7 on 2025-04-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0004_helpedneedy_collected_helpedneedy_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needyprofile',
            options={'verbose_name': 'Личный кабинет для нуждающегося', 'verbose_name_plural': 'Личный кабинет для нуждающегося'},
        ),
    ]
