# Generated by Django 5.1.6 on 2025-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='patients',
            field=models.ManyToManyField(to='jbr.needy', verbose_name='Нуждающийся'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='volunteer',
            field=models.ManyToManyField(to='jbr.volunteer', verbose_name='Волонтёр'),
        ),
    ]
