# Generated by Django 5.1.6 on 2025-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0005_alter_bankdetails_options_alter_founders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='BakaiBankImg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Бакай Банк лого'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='CompanionImg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Компанион лого'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='MbankImg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Мбанк лого'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='ObankImg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ОБанк лого'),
        ),
        migrations.AddField(
            model_name='patients',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Очень срочно', 'Очень срочно')], max_length=255, null=True, verbose_name='Насколько срочно'),
        ),
    ]
