# Generated by Django 5.1.7 on 2025-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0005_alter_dokumentsneedy_dokument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentsneedy',
            name='age',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokumentsneedy',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
