# Generated by Django 5.1.7 on 2025-03-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0006_dokumentsneedy_age_dokumentsneedy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentsneedy',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dokumentsneedy',
            name='name',
        ),
        migrations.AlterField(
            model_name='dokumentsneedy',
            name='dokument',
            field=models.FileField(upload_to='needy_profiles/dokuments/', verbose_name='Документ'),
        ),
    ]
