# Generated by Django 5.1.6 on 2025-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0006_remove_qrcode_patients_remove_qrcode_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': 'QR-код', 'verbose_name_plural': 'QR-коды'},
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='patients',
            field=models.ManyToManyField(to='jbr.needy', verbose_name='Нуждающиеся'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers_qr/', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='volunteer',
            field=models.ManyToManyField(to='jbr.volunteer', verbose_name='Волонтёры'),
        ),
    ]
