# Generated by Django 5.1.7 on 2025-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0007_remove_dokumentsneedy_age_remove_dokumentsneedy_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needyprofile',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='needy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jbr.needyprofile', verbose_name='Профиль'),
            preserve_default=False,
        ),
    ]
