# Generated by Django 5.1.6 on 2025-03-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0007_alter_qrcode_options_alter_qrcode_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='patients',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jbr.needy', verbose_name='Нуждающийся'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jbr.volunteer', verbose_name='Волонтёр'),
            preserve_default=False,
        ),
    ]
