# Generated by Django 5.1.7 on 2025-03-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0008_remove_needyprofile_volunteers_volunteer_needy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyprofile',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Сбор'),
        ),
        migrations.AlterField(
            model_name='needyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
