# Generated by Django 5.1.6 on 2025-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0008_remove_qrcode_patients_qrcode_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='patient',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='patients',
            field=models.ManyToManyField(to='jbr.needy', verbose_name='Нуждающиеся'),
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='volunteer',
            field=models.ManyToManyField(to='jbr.volunteer', verbose_name='Волонтёры'),
        ),
    ]
