# Generated by Django 5.1.6 on 2025-03-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0009_remove_qrcode_patient_qrcode_patients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='needy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jbr.needy', verbose_name='Банковские реквезиты для'),
            preserve_default=False,
        ),
    ]
