# Generated by Django 5.1.7 on 2025-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0009_alter_needyprofile_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='urls',
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_mumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
