# Generated by Django 5.1.6 on 2025-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0010_bankdetails_needy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Сбор открыт'),
        ),
    ]
