# Generated by Django 5.1.7 on 2025-03-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0010_remove_bank_urls_bank_phone_mumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='phone_mumber',
        ),
        migrations.AddField(
            model_name='bank',
            name='urls',
            field=models.URLField(default=1, verbose_name='Ссылка на банк'),
            preserve_default=False,
        ),
    ]
