# Generated by Django 5.1.7 on 2025-03-29 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0011_remove_bank_phone_mumber_bank_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='needy',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='needy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='jbr.needyprofile'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='assigned', max_length=20)),
                ('needy_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbr.needyprofile')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbr.volunteer')),
            ],
        ),
    ]
