# Generated by Django 5.1.7 on 2025-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0012_remove_volunteer_needy_volunteer_needy_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='needyprofile',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма для сбора'),
        ),
    ]
