# Generated by Django 5.1.6 on 2025-03-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0012_alter_needy_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='NeedyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('currency', models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль'), ('SOM', 'Сом')], default='SOM', max_length=3)),
                ('patients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jbr.needy', verbose_name='Личный кабинет')),
            ],
        ),
    ]
