# Generated by Django 5.1.6 on 2025-03-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0013_remove_volunteer_phone_number_needyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jbr.volunteer', verbose_name='Волонтёры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='needyprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль'), ('SOM', 'Сом')], default='SOM', max_length=3, verbose_name='Выберите валюту'),
        ),
        migrations.AlterField(
            model_name='needyprofile',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='Сумма для сбора'),
        ),
    ]
