# Generated by Django 5.1.6 on 2025-03-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0014_needyprofile_volunteer_alter_needyprofile_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRcode',
        ),
    ]
