# Generated by Django 5.1.6 on 2025-03-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0015_delete_qrcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needyprofile',
            options={'verbose_name': 'Личный кабинет', 'verbose_name_plural': 'Личный кабинет'},
        ),
    ]
