# Generated by Django 5.1.6 on 2025-03-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0016_alter_needyprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyprofile',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jbr.volunteer', verbose_name='Волонтёры'),
        ),
    ]
