# Generated by Django 5.1.6 on 2025-03-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0018_remove_needyprofile_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='needy_profiles/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
