# Generated by Django 5.1.6 on 2025-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0019_needyprofile_photo_delete_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='Собранная сумма'),
        ),
    ]
