# Generated by Django 5.1.6 on 2025-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0020_needyprofile_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Сбор'),
        ),
    ]
