# Generated by Django 5.1.6 on 2025-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0022_remove_needyprofile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
