# Generated by Django 5.1.6 on 2025-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0023_needyprofile_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyprofile',
            name='collected',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Собранная сумма'),
        ),
        migrations.AlterField(
            model_name='needyprofile',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Сумма для сбора'),
        ),
    ]
