# Generated by Django 5.1.6 on 2025-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0024_alter_needyprofile_collected_alter_needyprofile_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyprofile',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Сбор закрыт'),
        ),
    ]
