# Generated by Django 5.1.6 on 2025-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0025_alter_needyprofile_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Сбор'),
        ),
    ]
