# Generated by Django 5.1.6 on 2025-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0027_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('phone_number', models.IntegerField(default='+996', verbose_name='Наши контакты')),
                ('email', models.EmailField(default='user@gmial.com', max_length=254, verbose_name='@Email')),
                ('geolocation', models.URLField(verbose_name='Наш адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
