# Generated by Django 5.1.6 on 2025-03-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0029_alter_contacts_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needyprofile',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='needyprofile',
            name='currency',
        ),
    ]
