# Generated by Django 5.1.6 on 2025-03-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0030_remove_needyprofile_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Собранная сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needyprofile',
            name='currency',
            field=models.CharField(default=1, max_length=3, verbose_name='Выберите валюту'),
            preserve_default=False,
        ),
    ]
