# Generated by Django 5.1.6 on 2025-03-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0031_needyprofile_collected_needyprofile_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needyprofile',
            name='currency',
        ),
    ]
