# Generated by Django 5.1.6 on 2025-03-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0032_remove_needyprofile_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needyprofile',
            name='is_closed',
        ),
    ]
