# Generated by Django 5.1.6 on 2025-03-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0033_remove_needyprofile_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='needyprofile',
            name='diagnosis',
            field=models.TextField(default=1, verbose_name='Диагноз'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needyprofile',
            name='treatment',
            field=models.TextField(default=1, verbose_name='Требуется лечение'),
            preserve_default=False,
        ),
    ]
