# Generated by Django 5.1.6 on 2025-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0034_needyprofile_diagnosis_needyprofile_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needyprofile',
            name='diagnosis',
            field=models.CharField(max_length=255, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='needyprofile',
            name='treatment',
            field=models.CharField(max_length=255, verbose_name='Требуется лечение'),
        ),
    ]
