# Generated by Django 5.1.6 on 2025-03-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0036_needyprofile_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needyprofile',
            name='is_closed',
        ),
    ]
