# Generated by Django 5.1.6 on 2025-03-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbr', '0038_needyprofile_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='treatment',
            field=models.CharField(default=1, max_length=255, verbose_name='Требуется лечение'),
            preserve_default=False,
        ),
    ]
